spring:
  datasource:
    url: jdbc:h2:mem:ledgerdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
  
logging:
  level:
    root: INFO
    com.event.ledger: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
